debug: false

pipeline:
  docker:
    image: plugins/docker
    environment:
      - DOCKER_LAUNCH_DEBUG=false
    repo: uberamd/sensu-ubuntu
    tags:
      - latest
      - 1.0.2
    args:
      - SENSU_VERSION=1.0.2-1
    dockerfile: Dockerfile
    insecure: false
    secrets: [ docker_username, docker_password ]

